/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#00e5ff",
        "tertiary": "#fce6ff",
        "tertiary-fixed": "#f8d8ff",
        "on-primary": "#00363d",
        "on-tertiary-fixed": "#320047",
        "on-secondary-fixed": "#24005b",
        "secondary-fixed-dim": "#d1bcff",
        "on-primary-fixed-variant": "#004f58",
        "surface-container-high": "#2a2a2a",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "on-tertiary-container": "#9100c4",
        "surface": "#131313",
        "surface-container": "#201f1f",
        "on-secondary-container": "#d7c4ff",
        "secondary-container": "#6b07ef",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#bac9cc",
        "on-secondary-fixed-variant": "#5800c8",
        "on-secondary": "#3d0090",
        "on-tertiary-fixed-variant": "#74009f",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        "outline": "#849396",
        "secondary": "#d1bcff",
        "surface-container-low": "#1c1b1b",
        "tertiary-container": "#f0c0ff",
        "on-primary-fixed": "#001f24",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#00626e",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "primary-fixed": "#9cf0ff",
        "primary": "#c3f5ff",
        "surface-container-highest": "#353534",
        "secondary-fixed": "#eaddff",
        "inverse-primary": "#006875",
        "outline-variant": "#3b494c",
        "on-tertiary": "#520071",
        "primary-fixed-dim": "#00daf3",
        "tertiary-fixed-dim": "#ecb2ff",
        "surface-tint": "#00daf3",
        "on-surface": "#e5e2e1",
        "background": "#131313",
        "surface-bright": "#393939",
        "on-error": "#690005"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
